apiVersion: v1
kind: Service
metadata:
  name: popupshop-app-service
spec:
  selector:
    app: popupshop-app
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: popupshop-app
spec:
  selector:
    matchLabels:
      app: popupshop-app
  replicas: 3
  template:
    metadata:
      labels:
        app: popupshop-app
    spec:
      containers:
      - name: popupshop-app
        image: yourDockerAccount/popupshop-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888